# Note: You can use any Debian/Ubuntu based image you want. 
FROM mcr.microsoft.com/devcontainers/base:dev-bullseye

# Enable new "BUILDKIT" mode for Docker CLI
ENV DOCKER_BUILDKIT=1

# set welcome message
COPY welcome-message.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt